version: "2"
services:
  foo:
    privileged: true
    build: ./services/foo/.
    ports:
      - "5000:5000"
    environment:
      - BAR_ENDPOINT=http://bar:5000/bar
      - AGENT_HOSTNAME=otel-collector

  bar:
    privileged: true
    build: ./services/bar/.
    environment:
      - AGENT_HOSTNAME=otel-collector
 
  otel-collector:
    privileged: true
    image: docker.io/otel/opentelemetry-collector:0.25.0
    ports:
      - "6831:6831"
      - "14268:14268"
      - "4317:4317"
    volumes:
      - ./config/otel-collector.yaml:/config/otel-collector.yaml
    command:
      - chmod 777 /config/otel-collector.yaml
      - --config=/config/otel-collector.yaml

  tempo:
    privileged: true
    image: docker.io/grafana/tempo:0.7.0
    command: 
      - chmod 777 /etc/tempo.yaml
      - chmod 777 /tmp/tempo
      - "-config.file=/etc/tempo.yaml"
    ports:
      - "3100:3100"
      - "55680:55680"
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./example-data/tempo:/tmp/tempo

  grafana:
    image: docker.io/grafana/grafana:7.5.4
    command:
      - chmod 777 /etc/grafana/provisioning/datasources
    volumes:
      - /home/giulio/grafana/foobar-demo/config/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "8080:3000"
